#ifndef _CPP_COMPATIBILITY_ENABLE_SHARED_FROM_THIS_HPP_
#define _CPP_COMPATIBILITY_ENABLE_SHARED_FROM_THIS_HPP_

#include "prolog.hpp"

#if (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)
#   define CPP_COMPATIBILITY_NAMESPACE_ENABLE_SHARED_FROM_THIS                  std
#   include <memory>
#endif // (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)

#if (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))
#   ifndef CPP_COMPATIBILITY_NAMESPACE_ENABLE_SHARED_FROM_THIS
#       define CPP_COMPATIBILITY_NAMESPACE_ENABLE_SHARED_FROM_THIS              CPP_COMPATIBILITY_NAMESPACE
#   endif // CPP_COMPATIBILITY_NAMESPACE_ENABLE_SHARED_FROM_THIS

#   include "external_warnings_silence.hpp"
#   include "windows_sdk_headers.hpp"
#   include <boost/enable_shared_from_this.hpp>
#   include "external_warnings_reset.hpp"

namespace CPP_COMPATIBILITY_NAMESPACE
{
    using boost::enable_shared_from_this;
}

#endif // (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))

#endif // _CPP_COMPATIBILITY_ENABLE_SHARED_FROM_THIS_HPP_
