#ifndef _CPP_EXTENSIONS_EXTERNAL_WARNINGS_RESET_HPP_
#define _CPP_EXTENSIONS_EXTERNAL_WARNINGS_RESET_HPP_

#include "prolog.hpp"

#ifdef _MSC_VER
#   pragma warning(pop)
#endif // _MSC_VER

#endif // _CPP_EXTENSIONS_EXTERNAL_WARNINGS_RESET_HPP_
