#ifndef _CPP_COMPATIBILITY_SWAP_WEAK_PTR_HPP_
#define _CPP_COMPATIBILITY_SWAP_WEAK_PTR_HPP_

#include "prolog.hpp"

#if (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)
#   define CPP_COMPATIBILITY_NAMESPACE_SWAP_WEAK_PTR                            std
#   include <memory>
#endif // (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)

#if (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))
#   ifndef CPP_COMPATIBILITY_NAMESPACE_SWAP_WEAK_PTR
#       define CPP_COMPATIBILITY_NAMESPACE_SWAP_WEAK_PTR                        CPP_COMPATIBILITY_NAMESPACE
#   endif // CPP_COMPATIBILITY_NAMESPACE_SWAP_WEAK_PTR

#   include "swap.hpp"
#   include "weak_ptr.hpp"

#endif // (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))

#endif // _CPP_COMPATIBILITY_SWAP_WEAK_PTR_HPP_
