#ifndef _CPP_COMPATIBILITY_THREAD_HPP_
#define _CPP_COMPATIBILITY_THREAD_HPP_

#include "prolog.hpp"

#if (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)
#   include <thread>
#endif // (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)

#if (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))
#error todo
#include <boost/thread.hpp>

namespace CPP_COMPATIBILITY_NAMESPACE
{
    namespace this_thread = boost::this_thread;

    typedef boost::thread thread;
}

#endif // (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))

#endif // _CPP_COMPATIBILITY_THREAD_HPP_
