#ifndef _CPP_COMPATIBILITY_TYPE_TRAITS_HPP_
#define _CPP_COMPATIBILITY_TYPE_TRAITS_HPP_

#include "dialect.hpp"

#if (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)
#   define CPP_COMPATIBILITY_NAMESPACE_TYPE_TRAITS                              std
#endif // (CPP_COMPATIBILITY_DIALECT >= CPP_COMPATIBILITY_DIALECT_0X)

#if (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))

#   include "external_warnings_silence.hpp"
#   include "windows_sdk_headers.hpp"
#include <boost/type_traits.hpp>
#   include "external_warnings_reset.hpp"

#ifndef CPP_COMPATIBILITY_NAMESPACE_TYPE_TRAITS
#   define CPP_COMPATIBILITY_NAMESPACE_TYPE_TRAITS                              CPP_COMPATIBILITY_NAMESPACE
#endif // CPP_COMPATIBILITY_NAMESPACE_TYPE_TRAITS

namespace CPP_COMPATIBILITY_NAMESPACE
{
}

#endif // (defined(CPP_COMPATIBILITY_NO_STD_NAMESPACE) || (CPP_COMPATIBILITY_DIALECT < CPP_COMPATIBILITY_DIALECT_0X))

#endif // _CPP_COMPATIBILITY_TYPE_TRAITS_HPP_
